[package]
name = "client-yew"
version = "0.1.0"
edition = "2024"

[dependencies]
gloo-net = "0.6.0"
serde = { version = "1.0.219", features = ["derive"] }
wasm-bindgen-futures = "0.4.50"
yew = { version = "0.21.0", features = ["csr"] }
